Mission 2 Symfony/projetSicilySymfony/src/Entity/Tarifer.php
<?php

namespace App\Entity;

use App\Repository\TariferRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TariferRepository::class)
 */
class Tarifer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $tarif;

    /**
     * @ORM\ManyToOne(targetEntity=Type::class, inversedBy="tarifers")
     */
    private $Type;

    /**
     * @ORM\ManyToOne(targetEntity=Periode::class, inversedBy="tarifers")
     */
    private $Periode;

    /**
     * @ORM\ManyToOne(targetEntity=Liaison::class, inversedBy="tarifers")
     */
    private $Liaison;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTarif(): ?float
    {
        return $this->tarif;
    }

    public function setTarif(float $tarif): self
    {
        $this->tarif = $tarif;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->Type;
    }

    public function setType(?Type $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getPeriode(): ?Periode
    {
        return $this->Periode;
    }

    public function setPeriode(?Periode $Periode): self
    {
        $this->Periode = $Periode;

        return $this;
    }

    public function getLiaison(): ?Liaison
    {
        return $this->Liaison;
    }

    public function setLiaison(?Liaison $Liaison): self
    {
        $this->Liaison = $Liaison;

        return $this;
    }
}

Mission 2 Symfony/projetSicilySymfony/src/Controller/CompteController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\ReservationRepository;
use App\Repository\TraverseeRepository;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use App\Entity\User;
use App\Form\SettingsType;

class CompteController extends AbstractController
{

    //Fonction pour la route /compte
    public function index(): Response
    {
        return $this->render('compte/index.html.twig');
    }

    //Fonction pour la route /reservations
    public function reservations(ReservationRepository $reservationsRepository, UserInterface $user, TraverseeRepository $traverseeRepository): Response
    {
        $userId = $user->getId(); //Récupération de l'id de notre utilisateur connecté
        $reservations = $reservationsRepository->findBy(["user" => $userId]); // Récupération des réservation de notre utilisateur
        $travs = $traverseeRepository->findBy(["id" => $reservations]); // Récupération des traversées des réservations de notre utilisateur

        return $this->render('compte/reservations.html.twig',[
            'reservations' => $reservations, //Passage des reservations en paramètre du render
            'travs' => $travs, //Passage des traversées en paramètre du render
        ]);
    }

    //Fonction pour la route /reglages
    public function reglages(Request $request, ManagerRegistry $doctrine, UserInterface $user, UserPasswordEncoderInterface $passwordEncoder): Response
    {

        //Formulaire d'actualisation des infos de l'utilisateur
        $form = $this->createFormBuilder()

            //Champ (Input) de type texte ayant pour valeur l'username de l'utilisateur
            ->add('username', TextType::class,[
                'required' => true,
                'attr' => [
                    'value' => $user->getUsername(),
                ]
            ])

            //Champ de type Repeated afin d'avoir 2 champs du même type (ici password)
            ->add('password', RepeatedType::class,[
                'type' => PasswordType::class,
                'required' => false,
                'first_options' => ['label' => 'Nouveau mot de passe'],
                'second_options' => ['label' => 'Confirmez votre nouveau mot de passe'],
                
            ])

            //Champ de type submit afin d'envoyer les données du formulaire
            ->add('Confirmer', SubmitType::class,[
                'attr' => [
                    'class' => 'btn btn-success',
                    'onclick' => 'return confirm("Voulez vous modifier vos informations?")', //Demande de confirmation onclick
                ]
            ])

            //Formation du formulaire
            ->getForm()

        ;

        //Récupération de la requête envoyée
        $form->handleRequest($request);

        //Vérification si le formulaire à été submit 
        if ($form->isSubmitted()){

            //Variable data récupère les données saisie dans le formulaire
            $data = $form->getData();

            //Actualisation du username de l'utilisateur
            $user->setUsername($data['username']);

            //Récupération & Cryptage du password saisi
            $user->setPassword(
                $passwordEncoder->encodePassword($user, $data['password'])
                );    
            
            //Entity Manager 
            $em = $doctrine->getManager();
            //Persistance des données de notre utilisateur
            $em->persist($user);
            //Application des changements
            $em->flush();

            //Redirection à la page reglage
            return $this->redirect($this->generateUrl('reglages'));
        }

        return $this->render('compte/reglages.html.twig', [
            'reglages' => $form->createView(), // Création du formulaire avec createView() puis envoi vers la page reglages
        ]);
    }

}

Mission 2 Symfony/projetSicilySymfony/templates/compte/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Compte{% endblock %}

{% block content %}

<div class="container">
    {% if app.user %}
        <center><br><br>
        <h5>Bonjour et bienvenue sur votre compte {{ app.user.username }}!</h5>
        </center>
    {% endif %}
</div>
{% endblock %}

Mission 2 Symfony/projetSicilySymfony/templates/compte/reglages.html.twig
{% extends 'base.html.twig' %}



{% block title %}Réglages{% endblock %}

{% block content %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
{% if is_granted("ROLE_USER") %}

       <h3>Réglages :</h3>

    {{ form(reglages) }}
    

{% else %}
<h1>Oups ! Une erreur s'est produite :/</h1>
{% endif %}
</div>
{% endblock %}

Mission 2 Symfony/projetSicilySymfony/templates/compte/reservations.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservations{% endblock %}

{% block content %}
<body id="bgResa">
<center>
<div id="bgResa">
<br><br>
{% if is_granted("ROLE_USER") %}
    <div id="listResa">
        <div class="container bg-light border rounded mt-5">
            <div class="row pt m-1">
                <h3>Voici la liste de vos réservations :</h3>
            </div>
        </div>
    </div>
    <br><br>
    {% for resa in reservations %}
    <div class="card" id="resaCard">
        <img class="card-img-top" src={{ asset('assets/images/bateaux.jpg') }} alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">SicilyLines ⛵</h5>
            <p class="card-text">Votre réservation part de {{ resa.traversee.liaison.portDepart.nom }} jusqu'à {{ resa.traversee.liaison.portArrivee.nom }} <br>
            Le départ est prévu pour {{ resa.traversee.heure|date('H:i') }}, 
            d'une durée de {{ resa.traversee.liaison.duree|date('H:i') }}
            le {{ resa.traversee.date|date('d-m-Y') }}<br>
            à bord du bateau {{ resa.traversee.bateau.nom }}</p>
        </div>
    </div>
    {% endfor %}

{% else %}
<h1>Oups ! Une erreur s'est produite :/</h1>
{% endif %}

</div>
</center>
</body>
{% endblock %}